name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag quay.io/topicus_zorg/debug-https:$(date +%s)
    - name: Login on Quay.io
      run: docker login -u="${QUAY_DEBUG_TLS_ROBOT_USERNAME}" -p="${QUAY_DEBUG_TLS_ROBOT_PASSWORD}" quay.io
    - name: Push the Docker image
      run: docker push quay.io/topicus_zorg/debug-https:$(date +%s)
